#!/usr/bin/perl

use strict;
use warnings;
use File::Spec;
use File::Path qw(make_path remove_tree);
use Cwd qw(abs_path);
use POSIX qw(strftime);

# Need change pahths for live!
use constant {
  DOCKER_COMPOSE_FILE_PATH  =>"/home/matthiaspi/docker-compose.yml",
  BACKUP_DESTINATION_DIR    =>"/home/matthiaspi",
  LOG_FILE                  =>"/tmp/temp.log",
  DOCKER_PATH               =>"/var/lib/docker",
  TEMP_DIR                  =>"/home/matthiaspi/temp_backup_dir",
};

use constant {
    TX_BACKUP_START         =>"[Info] The Backup started! ",
    TX_FINISHED_BACKUP      =>"[Info] Backup is done! ",
    TX_FAILED_BACKUP        =>"[Info] Failed to create backup ",
    TX_NO_VOLUMES_FOUND     =>"[Info] No Volumed found to backup ",
    TX_CREATING_SINGLE_TAR  =>"[Info] Creating single tar for all containers ",
};

sub main() {
    _PrintAndLog(TX_BACKUP_START());
    _CheckBackupDestination();
    my @volume_names = _GetVolumeNames();
    _AggregateVolumes(@volume_names);

    _CreateSingleBackup();
    
}

sub _GetVolumeNames {
    my @volume_names = `docker volume ls -q`;
    chomp(@volume_names);
    return @volume_names;
}

sub _GetTime {
    return strftime "%Y%m%d%H%M%S", localtime;
}

sub _AggregateVolumes() {
    my (@volume_names) = @_;

    # Ensure the temp directory exists and is empty
    remove_tree (TEMP_DIR());
    make_path (TEMP_DIR());

    foreach my $volume_name (@volume_names) {
        my $volume_data_path = File::Spec->catfile(DOCKER_PATH, "volumes", $volume_name, "_data");
        my $destination_path = File::Spec->catfile(TEMP_DIR() , $volume_name);
        system("cp -a $volume_data_path/. $destination_path/");
    }
}

sub _CreateSingleBackup() {
    my $timestamp = _GetTime();
    my $backup_filename = "docker_volumes_backup_${timestamp}.tar.gz";
    my $backup_path = File::Spec->catfile(BACKUP_DESTINATION_DIR(), $backup_filename);   
    _PrintAndLog(TX_CREATING_SINGLE_TAR());
    system("tar -czf $backup_path -C " . TEMP_DIR() . " .");

    if ($? == 0) {
        _PrintAndLog(TX_FINISHED_BACKUP() . "$backup_path");
    } else {
        _PrintAndLog(TX_FAILED_BACKUP() . "$backup_path");
    }

    # Optionally, clean up the temporary directory after backup
    remove_tree(TEMP_DIR());
}
sub _CheckBackupDestination {
    my $backup_dir = BACKUP_DESTINATION_DIR;

    unless (-d $backup_dir && -w $backup_dir) {
        die "Backup destination $backup_dir does not exist or is not writable.\n";
    }

    _PrintAndLog("[Info] Backup destination $backup_dir is ready.");
}

sub _PrintAndLog($) {
    my($givenLine)=@_;
    my $line = localtime().":\t".$givenLine;

    print $line."\n";
    return unless open FILE,">>".LOG_FILE();
    print FILE $line."\n";
    close FILE;
  }
  main();
